# Smart Bulb Adress
SMART_BULB_IP_ADRESS = '192.168.99.105' # 
SMART_BULB_PORT      = 55443

# MQTT Broker configuration
# Note: All robots (EVA and FRED) will access the broker through the IP 192.168.99.100
MQTT_BROKER_ADRESS      = '127.0.0.1' # Acer Laptop IP address # Ip adress (Fred router) 192.168.99.100
MQTT_PORT               = 1883

SIMULATOR_TOPIC_BASE    = 'SIMULATOR'

# Default audio file extension.
AUDIO_EXTENSION = ".mp3"

# Audio format generated by IBM Watson (file extension).
WATSON_AUDIO_EXTENSION = ".mp3"
ACCEPT_AUDIO_EXTENSION = "audio/mp3"

# Default voice (language) for the IBM Watson service.
# pt_BR-faber-medium, en_US-amy-medium e en_US-ryan-medium - Utilizam o Piper
VOICE_TYPE = "en_US-amy-medium" # "pt-BR_IsabelaV3Voice" 
PITCH_SHIFT = "0"

# Default language for Google translating
LANG_DEFAULT_GOOGLE_TRANSLATING = "PT"
